dataset_name: celeba
attack: benign
device: cuda:0
batch: 64
epoch: 700000
save_epoch: 10000
sample_epoch: 100000
lr: 8e-5
loss_type: l2
sample_type: ddim
image_size: 64
server: pc
grad_acc: 1
parallel: 0
path: None

unet:
  dim: 128
  dim_mults: (1, 1, 2, 2, 4)
  dropout: 0

diffusion:
  timesteps: 1000
  sampling_timesteps: 250
  beta_schedule: sigmoid

# only backdoor diffusion will use this
ratio: 0.1
gamma: 1e-3
p_start: 200
p_end: 400